name = input('What is your name? :')
surname = input('what is your surname? :')
a = input('what is your Chan Pee? :')
ID = input('what is your ID pass? :')
print('Hi,%s.'% name)
print('   %s.'%surname)
print('Chan pee  %s.\n.'%a )
print('ID pass  %s.\n.'%ID)
#print('Welcome to Python.')
