a = input('input your first number :')
b = input('input your second number :')
c = input('input your third number :')
d = input('input your forth number :')
e = input('input your fifth number :')
a1 = float(a)
a2 = complex(a)
b1 = float(b)
b2 = complex(b)
c1 = float(c)
c2 = complex(c)
d1 = float(d)
d2 = complex(d)
e1 = float (e)
e2 = complex(e)
print('float of %s equal '%a,a1)
print('complex of %s equal'%a,a2)
print('float of %s equal '%b,b1)
print('complex of %s equal'%b,b2)
print('float of %s equal '%c,c1)
print('complex of %s equal'%c,c2)
print('float of %s equal '%d,d1)
print('complex of %s equal'%d,d2)
print('float of %s equal '%e,e1)
print('complex of %s equal'%e,e2)